language: java

jdk:
  - openjdk16


#sudo: false

env:
  global:
    -CODECOV_TOKEN='6df51d2a-7a56-4f2e-a100-570d39128181'
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - glavstroi_e@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - memcached
  - postgresql


# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres