language: java

jdk:
  - openjdk16


#sudo: false

env:
  global:
#    -CODECOV_TOKEN="dabfa32f-84b6-487e-802e-f49b05a380b3"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - glavstroi_e@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres